### ISSUE TITLE
support for nativescript

### ISSUE THREAD

**Issue by jonathanmeguira** [a8m/ng-pipes#16]
is this module supported on nativescript? if not it would be great to have that available for nativescript as well

**Comment by SteveVanOpstal** [comment]
It seems like NativeScript has two implementations:
* https://github.com/NativeScript/nativescript-angular, the angular integration
ng-pipes will work on this because they use the angular framework with NativeScript components.
* https://github.com/NativeScript/NativeScript, a javascript framework
This looks like an entirely different framework and therefore ng-pipes is not compatible with it.

**Comment by jonathanmeguira** [comment]
Thank you
